github:
  prebuilds:
    branches: true

tasks:
  - init: |
      pyenv install 3.10
      pyenv global 3.10
      pipenv install --deploy --dev
  - command: pipenv shell

vscode:
  extensions:
    - ms-python.python