gitConfig:
  core.editor: nano
  user.email: 46974369+KotUW@users.noreply.github.com

image: gitpod/workspace-python-3.10

tasks:
  - init: pipenv install --dev
  - command: pipenv shell

vscode:
  extensions:
    - ms-python.python
